--------------------------------------------------------
--  File created - Friday-April-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence INGREDIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "POMODOROROSSO"."INGREDIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table INGREDIENTE
--------------------------------------------------------

  CREATE TABLE "POMODOROROSSO"."INGREDIENTE" 
   (	"ID_INGREDIENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"UNIDAD_MEDIDA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDEN_COMPRA
--------------------------------------------------------

  CREATE TABLE "POMODOROROSSO"."ORDEN_COMPRA" 
   (	"ID_ORDEN" NUMBER(*,0), 
	"NOMBRE_CLIENTE" VARCHAR2(255 BYTE), 
	"FECHA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDEN_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" 
   (	"ID_ORDEN" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "POMODOROROSSO"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"PRECIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO_INGREDIENTE
--------------------------------------------------------

  CREATE TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" 
   (	"ID_PRODUCTO" NUMBER(*,0), 
	"ID_INGREDIENTE" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into POMODOROROSSO.INGREDIENTE
SET DEFINE OFF;
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (4,'Paltas','C/U');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (5,'Pepino','C/U');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (6,'Masa Dulce','Gr');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (7,'Aceitunas','C/U');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (8,'Mayonesa','Gr');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (3,'Queso Muzzarela','Fetas');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (1,'Masa de tarta','Gr');
Insert into POMODOROROSSO.INGREDIENTE (ID_INGREDIENTE,NOMBRE,UNIDAD_MEDIDA) values (2,'Paleta','Fetas');
REM INSERTING into POMODOROROSSO.ORDEN_COMPRA
SET DEFINE OFF;
REM INSERTING into POMODOROROSSO.ORDEN_PRODUCTO
SET DEFINE OFF;
REM INSERTING into POMODOROROSSO.PRODUCTO
SET DEFINE OFF;
Insert into POMODOROROSSO.PRODUCTO (ID_PRODUCTO,NOMBRE,PRECIO) values (1,'Torta de Fiambre',500);
REM INSERTING into POMODOROROSSO.PRODUCTO_INGREDIENTE
SET DEFINE OFF;
Insert into POMODOROROSSO.PRODUCTO_INGREDIENTE (ID_PRODUCTO,ID_INGREDIENTE,CANTIDAD) values (1,1,500);
Insert into POMODOROROSSO.PRODUCTO_INGREDIENTE (ID_PRODUCTO,ID_INGREDIENTE,CANTIDAD) values (1,2,25);
Insert into POMODOROROSSO.PRODUCTO_INGREDIENTE (ID_PRODUCTO,ID_INGREDIENTE,CANTIDAD) values (1,3,25);
--------------------------------------------------------
--  DDL for Index SYS_C009365
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009365" ON "POMODOROROSSO"."INGREDIENTE" ("ID_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009368
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009368" ON "POMODOROROSSO"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009372
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009372" ON "POMODOROROSSO"."PRODUCTO_INGREDIENTE" ("ID_PRODUCTO", "ID_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009376
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009376" ON "POMODOROROSSO"."ORDEN_COMPRA" ("ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009380
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009380" ON "POMODOROROSSO"."ORDEN_PRODUCTO" ("ID_ORDEN", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009365
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009365" ON "POMODOROROSSO"."INGREDIENTE" ("ID_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009376
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009376" ON "POMODOROROSSO"."ORDEN_COMPRA" ("ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009380
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009380" ON "POMODOROROSSO"."ORDEN_PRODUCTO" ("ID_ORDEN", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009368
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009368" ON "POMODOROROSSO"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009372
--------------------------------------------------------

  CREATE UNIQUE INDEX "POMODOROROSSO"."SYS_C009372" ON "POMODOROROSSO"."PRODUCTO_INGREDIENTE" ("ID_PRODUCTO", "ID_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INGREDIENTE
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."INGREDIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."INGREDIENTE" MODIFY ("UNIDAD_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."INGREDIENTE" ADD PRIMARY KEY ("ID_INGREDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."ORDEN_COMPRA" MODIFY ("NOMBRE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."ORDEN_COMPRA" ADD PRIMARY KEY ("ID_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDEN_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" ADD PRIMARY KEY ("ID_ORDEN", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."PRODUCTO" ADD PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO_INGREDIENTE
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" MODIFY ("ID_INGREDIENTE" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" ADD PRIMARY KEY ("ID_PRODUCTO", "ID_INGREDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" ADD FOREIGN KEY ("ID_ORDEN")
	  REFERENCES "POMODOROROSSO"."ORDEN_COMPRA" ("ID_ORDEN") ENABLE;
  ALTER TABLE "POMODOROROSSO"."ORDEN_PRODUCTO" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "POMODOROROSSO"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO_INGREDIENTE
--------------------------------------------------------

  ALTER TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "POMODOROROSSO"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "POMODOROROSSO"."PRODUCTO_INGREDIENTE" ADD FOREIGN KEY ("ID_INGREDIENTE")
	  REFERENCES "POMODOROROSSO"."INGREDIENTE" ("ID_INGREDIENTE") ENABLE;
